### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Nolij** [SrRapero720/chloride#1]
The licensing of this project has multiple issues. The [CurseForge page for this mod](https://legacy.curseforge.com/minecraft/mc-mods/embeddium-plus) lists [WTFPL](https://legacy.curseforge.com/project/931925/license) as the license, but this GitHub repo contains no license file. By not including a license file in the repository, this technically renders the project as ARR (All Rights Reserved), which means no permissions have been given to users. This should be addressed.

Additionally, this mod is forked from [Magnesium/Rubidium Extras](https://github.com/anthxnymc/MagnesiumExtras), which has its own licensing issues (which I have reported [in this issue](https://github.com/anthxnymc/MagnesiumExtras/issues/56)). Regardless of that, the terms of the WTFPL are not included in that mod's repo or on its CurseForge page, so it is arguably not available under WTFPL (despite its mods.toml claiming otherwise). Thus, distributing this project under WTFPL violates the license of its parent project, Magnesium/Rubidium Extras. If you wish to continue (legally) using WTFPL for this mod, you must remove all code taken from Magnesium/Rubidium Extras, or get the developer of that mod to distribute that code to you under WTFPL. Otherwise, I would advise use of LGPL-3.0, or whatever license Magnesium/Rubidium Extras switches to after they close the issue I opened regarding their licensing.

**Comment by SrRapero720** [comment]
i am aware of it. thanks for the report

**Comment by SrRapero720** [comment]
My personal decision was ignore this until Anthxny's fixes this issue on his side, so i can do any movement. i'll keep this open until become important to solve.

Btw, current refactor of code may avoid this issue.
