### ISSUE TITLE
1.2.0 update crashes my game

### ISSUE THREAD

**Issue by littlepianist** [SrRapero720/chloride#14]
I updated from 1.20.1/1.1.0 to 1.20.1/1.2.0 and the game crashed before fully loaded into menu screen
[crash-2024-01-08_12.33.51-client.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13856289/crash-2024-01-08_12.33.51-client.txt)

**Comment by SrRapero720** [comment]
your crash point to NoChatReports, not to Emb++
`Caused by: java.lang.NullPointerException: Cannot invoke "com.aizistral.nochatreports.common.platform.PlatformProvider.getConfigDir()" because the return value of "com.aizistral.nochatreports.common.NCRCore.getProvider()" is null`

**Comment by littlepianist** [comment]
Weird, I have no issues with no chat report before updating embeddium ++, but I will still try to open an issue on their side

**Comment by SrRapero720** [comment]
aparently curseforge adds extra dependency to all versions except 1.20.1. now is fixed
