### ISSUE TITLE
Betterfoliage leaf transparency is broken in 1.18.2/v1.2.0.

### ISSUE THREAD

**Issue by sakuraimikoto33** [SrRapero720/chloride#15]
In 1.1.0, it was possible to accurately transmit the leaves by setting Leaves Quality to Fancy, but in 1.2.0, it is not possible to do so.

1.1.0 Fast
![2024-01-08_16 05 55](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/5c07e63b-9b79-40f3-b6b9-fb06fbfa16ff)
1.1.0 Fancy
![2024-01-08_16 05 48](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/93e702af-1a06-4da6-b692-4f1480104fac)

1.2.0 Fast
![2024-01-08_16 09 41](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/5c0cb424-37a2-4fed-aab9-6e50dd194247)
1.2.0 Fancy
![2024-01-08_16 09 47](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/5b8a83db-9be9-4b77-a30e-5d8160922582)

**Comment by SrRapero720** [comment]
>  it is not possible to do so.

you mean config on video settings is missing? or you mean isn't possible to do that anymore?
in any case i'll look asap

**Comment by sakuraimikoto33** [comment]
The video settings exist, but the leaf display does not change even if you change them.

installed mods
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/c1ae913c-6cee-4be5-91ec-592a655e82a7)
I tried removing the selected mod, but it did not improve the issue.

**Comment by SrRapero720** [comment]
can you send me your logs? looks like i broke some forge code

**Comment by sakuraimikoto33** [comment]
[debug.log](https://github.com/SrRapero720/EmbeddiumPlus/files/13857351/debug.log)

**Comment by SrRapero720** [comment]
Tested on my side: mod works standalone with emb, emb++ and emd options
using fancy graphics... leaves quality doesn't do nothing

![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/29090346/fe1517d6-1c08-41ff-9bd1-ae37eaeffaed)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/29090346/3fb780b3-8db4-45ba-926d-eced7c510365)

**Comment by sakuraimikoto33** [comment]
I see...
If I set the graphics setting to Fancy, it displayed correctly.
Previously (1.1.0), it was displayed even if the graphics setting was set to Fast and the leaves quality was set to Fancy.

Anyway, thanks for testing how to get it working properly.

1.2.0
![2024-01-08_18 12 44](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/8785b0f2-562e-4fb4-8d84-5e80db147f9a)
![2024-01-08_18 12 50](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/43e644a2-be55-4198-9d9e-e5243f3b8d3a)

1.1.0
![2024-01-08_18 17 35](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/383f4824-6a36-445d-a374-e2fcdded3a61)
