### ISSUE TITLE
Transparency issues

### ISSUE THREAD

**Issue by sakuraimikoto33** [SrRapero720/chloride#16]
Similar issue to https://github.com/SrRapero720/EmbeddiumPlus/issues/15 , but after updating to 1.2.0, there is a problem with Biomes O' Plenty grass not being processed transparently.

The graphics setting is not displayed correctly even if the graphics setting is set to Fancy.
1.1.0
![2024-01-08_19 13 31](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/33e9ddc7-319d-4fa0-9424-9d9f75eafc03)
![2024-01-08_19 29 47](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/06e497dd-0371-4498-9e7b-4de0f0d59f62)

1.2.0
![2024-01-08_19 12 24](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/1532d42b-41f5-41a4-81df-688e0d4484c3)
![2024-01-08_19 21 18](https://github.com/SrRapero720/EmbeddiumPlus/assets/144892831/8398dca2-a9ad-46da-bb34-8a4f18c12ff8)

**Comment by CelestialAbyss** [comment]
I have not been able to reproduce this issue even after updating to 1.2.0.

**Comment by sakuraimikoto33** [comment]
> I have not been able to reproduce this issue even after updating to 1.2.0.

Can I ask you to tell me the video settings and MC version?
I am 1.18.2

**Comment by CelestialAbyss** [comment]
I am on 1.19.2 with the default video settings. Setting graphics to Fancy or Fast did not make a difference but I'm still a bit unsure how this is occurring for you

**Comment by sakuraimikoto33** [comment]
I created a clean profile with 1.18.2 and tried it with full initial settings, but the problem still occurs.

BoP 1.18.2 has stopped updating, and there may be a problem with BoP itself or compatibility, but at least it was working properly with 1.1.0.

**Comment by SrRapero720** [comment]
try with the 1.2.1
turning off performance mixins. is the only thing different on 1.18.2

- CurseForge: https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023086
- Modrinth: https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.1

**Comment by sakuraimikoto33** [comment]
I was able to confirm that turning off the performance mixins in 1.2.1 fixed the issue.
Thank you~
