### ISSUE TITLE
Some chests are not rendered in inventory even when FastChest is turned off

### ISSUE THREAD

**Issue by NeuTraLZero** [SrRapero720/chloride#18]
This includes Ender Chests and Treasure Chests and Chest Mimics from The Aether (but not Trapped Chests)

![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/43245485/ab9622bb-36f5-4dcc-8b58-5d86c58a651b)

**Comment by SrRapero720** [comment]
good decision make that feature toggleable
ask to the mod author if he can make a fix, only have to add chest resources as a normal block.

otherwise, i will fix it in one month, but i had to attach aether resources on my mod, so is not the most ideal thing

**Comment by SrRapero720** [comment]
Consider report this to the aether creators, they have to add chests as a normal block resource (adding block model and chest textures onto atlases)

i preffer avoid any problem related to include resources from other mods, use minecraft resources (for minecraft) is ok (i guess)

**Comment by SrRapero720** [comment]
and if you ask, yes, i consider this as an option to a fix, but is not a hard fix on the other side

**Comment by NeuTraLZero** [comment]
This happens without Aether installed as well, so I don't see why that would be an Aether problem.

I also tried disabling block entity culling and that doesn't work either

**Comment by SrRapero720** [comment]
your picture show a Aether chest no rendering, no other kind of chests.
i didn't get any similar report... can you test few content mods with chest and emb++

**Comment by NeuTraLZero** [comment]
I found the real cause. It happens only when I have one of the VanillaTweaks pack enabled, think It was either the "Proper Break Particles" or "Corrected Item Holding", probably the former
Just to be clear this only happens since Embeddium++ 1.2.0

**Comment by SrRapero720** [comment]
well, that was expected, 1.2.0 introduces chests feature

**Comment by GoldenFlame0** [comment]
+1 to being caused by VanillaTweaks.

**Comment by SrRapero720** [comment]
Report issue to VanillaTweaks then
