### ISSUE TITLE
most recent embeddium plus (1.2.0) makes blockentities on valkyrien skies ships go invisible

### ISSUE THREAD

**Issue by poly-1810** [SrRapero720/chloride#19]
not too much to really about this, back in embeddium plus 1.1.0 in order to fix this bug you just had to turn off max entity distance, but now there is no way to fix it
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/105131270/91b26528-29c9-4c2a-bee1-5ad18445150b)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/105131270/256cde6c-a9a6-4a8c-828b-8a16e1ef7a42)

**Comment by poly-1810** [comment]
normally the tracks are a bit more visible, i just didnt have an image on hand at the moment
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/105131270/8b021623-b82c-4158-b872-0b8a7d222ec8)

**Comment by emanuele246gi** [comment]
The same happens with Snow! Real Magic! blocks

**Comment by SrRapero720** [comment]
hello guys, thats why i add a whitelist
if you use a modpack probably author sets all modded entities as a "not cull"

1.2.0 re-writes the config, so, the most fashionable way to get it work backk is adding vs-eureka entities back again
just go into the `config/embeddium++.toml`, search `entityCulling -> whitelist` and add all VS entities using wildcards like `minecraft:*`

**Comment by poly-1810** [comment]
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/105131270/51a45e6d-5b8b-4830-95fb-48ab49428edf)
@SrRapero720 ive set the configs to not block the mods and even then treads from trackwork are still invisible

**Comment by SrRapero720** [comment]
@poly-1810 you restarted game¡?

**Comment by poly-1810** [comment]
main issue here tho is that it only vanishes on valkyrien skies 'ships', if theyre placed in the world theyre just fine but only when its simulated by the 'ships' is when it is entirely gone

**Comment by poly-1810** [comment]
> @poly-1810 you restarted game¡?

several times

**Comment by poly-1810** [comment]
i will be bringing this up with potato and the valkyrien skies team, but im 60% certain that the issue is with embeddium plus

**Comment by SrRapero720** [comment]
just to be more clear, turning off entity culling get it back again? and add it on whitelist doesn't work... right?

**Comment by poly-1810** [comment]
only in version 1.1.0, turning off entity culling brought it back. in version 1.2.0, turning off entityculling does nothing to fix it, and whitelist doesnt fix it either

**Comment by poly-1810** [comment]
ill provide a quick few modfiles for you if you would like as well, for testing, ill just need to compress to zip and prolly link it

**Comment by poly-1810** [comment]
https://drive.google.com/file/d/1oEW0TjyX_wPzw1R1a_hW2_FXLhMQ45Rf/view?usp=sharing

**Comment by SrRapero720** [comment]
disabling block entity culling fixes it?

**Comment by SrRapero720** [comment]
well NVM i am just an idiot, i forgot to check config for block entities.

i didn't do any change on entity max distance, EXCEPT on Block entities, i split on different.
also, i guess i can't just keep it as a rigid option, so i will add a whitelist to ignore weird mods doing weird things to render weird blocks :P

**Comment by emanuele246gi** [comment]
Thank you man, I will wait for the new version ^^

**Comment by poly-1810** [comment]
@SrRapero720 so you got it all fixed and should be patched in next release? if so, awesome, ill be sure to test it and report if its fixed once the next release is out

**Comment by SrRapero720** [comment]
## FIXED IN 1.2.1 - DOWNLOAD FROM
- CurseForge: [1.18.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023086) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023094) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023095)
- Modrinth: [1.18.2](https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.1) | [1.19.2](https://modrinth.com/mod/embeddiumplus/version/1.19.2-v1.2.1) | [1.20.1](https://modrinth.com/mod/embeddiumplus/version/1.20.1-v1.2.1)
