### ISSUE TITLE
[1.20.1 Forge] New Embeddium update might cause ocassional startup crash w/borderless windowed fullscreen.

### ISSUE THREAD

**Issue by PlayfulPiano** [SrRapero720/chloride#2]
(embeddium just updated to 0.2.10)

[crash-2023-11-23_20.42.10-client.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13454368/crash-2023-11-23_20.42.10-client.txt)

**Comment by SrRapero720** [comment]
Forge bug confirmed, earlyloadingscreen begin funny ¯\\_(ツ)_/¯
