### ISSUE TITLE
[Forge 47.2.0] Minecraft 1.19.2 - The new 1.2.0 overhaul update crashes while "Loading mods"

### ISSUE THREAD

**Issue by UnderPixel1475** [SrRapero720/chloride#20]
So, basically, when I have the 1.2.0 version of EmbeddiumPlus installed, my MC just freezes on "Loading mods", then closes and then gives me this debug.log and this crash-report .txt files:

[debug.log](https://github.com/SrRapero720/EmbeddiumPlus/files/13867480/debug.log)

[crash-2024-01-08_21.35.40-client.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13867481/crash-2024-01-08_21.35.40-client.txt)

Keep in-mind that: this is most likely not a version with the version of the mod, as I tried downgrading to 1.1.0 and it just did the same thing. Going as far as giving me the same debug.log and the same crash-report .txt files.

Also, if it is of any help, I have the Forgified Fabric API 0.91.0+1.10.4 installed.

![Screenshot_1](https://github.com/SrRapero720/EmbeddiumPlus/assets/124472837/e8160774-9c7c-4b0d-8aac-27050a489e8b)

Edit: My bad, I forgot to give a .txt file for my modlist, here it is:

[modlist.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13867510/modlist.txt)

**Comment by SrRapero720** [comment]
you are using emb++ 1.19.2 on your 1.20.1 setup

**Comment by UnderPixel1475** [comment]
BRUUUUUUUH, I am ACTUALLY STUPID, I am so SORRY LOL, I just have multiple modpacks and most of them are 1.19.2, so I ended up mixing things up and aaargghhh, wasn't able to replicate the actual issue. Yes, I still am having a issue by the way, it's just different then this and less dumb and now I am using emb++ for 1.20.1. You see, now when I try to join my world, instead of it going all the way through the whole "Joining world" proccess, after some seconds of waiting it just says "Saving world" then my MC closes, also I haven't changed anything regarding my MC, still the same Forge version and the same mods, (except now I have the correct version of EmbeddiumPlus lmao). Here's the crash-report and the debug.log: 

[debug.log](https://github.com/SrRapero720/EmbeddiumPlus/files/13868150/debug.log)

[crash-2024-01-08_23.24.55-client.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13868159/crash-2024-01-08_23.24.55-client.txt)

And here's the .txt file for my modlist for convenience ig:

[modlist.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13868169/modlist.txt)

**Comment by SrRapero720** [comment]
Workaround is turn off FPS display until I fix the issue

**Comment by UnderPixel1475** [comment]
I understand and take your time. Also mind if I ask, is that a mod I have or a feature from emb++?

**Comment by SrRapero720** [comment]
Feature of Emb++

**Comment by UnderPixel1475** [comment]
> Feature of Emb++

I imagined so, if so, I can turn it off in the video settings I assume?

**Comment by SrRapero720** [comment]
In video settings, set FPS display to OFF.

**Comment by UnderPixel1475** [comment]
Alright, thanks a bunch man, good luck on fixing this issue

**Comment by 5stigma** [comment]
same problem here, crash in 1.19.2, I will try to isolate the issue mod

**Comment by SrRapero720** [comment]
@5stigma instead of say "same problem here". send your crash report and your log file (using https://gist.github.com/) to determinate if is the same problem or is a different issue who needs a separated issue :P

**Comment by 5stigma** [comment]
[crash-2024-01-09_16.26.03-client.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13880892/crash-2024-01-09_16.26.03-client.txt)
Here. Anyway, I will try to find out if the issue is with another Mod

If you need to know anything more about my modpack, you can tell me, since it is very extensive

**Comment by 5stigma** [comment]
I disabled FPS sampling and it keeps crashing

**Comment by SrRapero720** [comment]
issue has been fixed. queue to 1.2.1 release (Don't ask ETA's)

**Comment by SrRapero720** [comment]
## FIXED IN 1.2.1 - DOWNLOAD FROM
- CurseForge: [1.18.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023086) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023094) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5023095)
- Modrinth: [1.18.2](https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.1) | [1.19.2](https://modrinth.com/mod/embeddiumplus/version/1.19.2-v1.2.1) | [1.20.1](https://modrinth.com/mod/embeddiumplus/version/1.20.1-v1.2.1)
