### ISSUE TITLE
[Question] Difference in FPS Dislpay with ModernUI mod installed

### ISSUE THREAD

**Issue by qznfbnj** [SrRapero720/chloride#24]
When [ModernUI](https://www.curseforge.com/minecraft/mc-mods/modern-ui) installed, there is difference in FPS Dislpay between 1.2.0 and 1.2.1.
I want to know what is causing the non-smoothing of the FPS text font in the 2.2.1 picture.
# 1. v1.2.0 w/ ModernUI
![2024-01-11_12 23 10](https://github.com/SrRapero720/EmbeddiumPlus/assets/100760086/e8ea28f0-e51d-444b-9a34-8b2f3ac66aa8)
# 2. v1.2.1 w/ ModernUI
## 2.1 No force Unicode
![2024-01-11_12 25 08](https://github.com/SrRapero720/EmbeddiumPlus/assets/100760086/38bc7c92-f62d-424c-90fe-75a42619049e)
### 2.2.1 Allow Shadow (ModernUI's feature)
Allow Shadow is a feature of ModernUI that seems to inadvertently override EmbeddiumPlus' Font Shadows feature.
![2024-01-11_12 25 22](https://github.com/SrRapero720/EmbeddiumPlus/assets/100760086/116212b0-17f3-448a-92d9-cb7264b3d3ee)
### 2.2.2 No Allow Shadow
![2024-01-11_12 29 58](https://github.com/SrRapero720/EmbeddiumPlus/assets/100760086/1426f472-b5da-4945-8a5c-db5211e377bf)

**Comment by SrRapero720** [comment]
basically i rewrite entire FPS display feature. and aparently drawString uses RGBA instead of ARGB (thats why background color looks as a solid bar)

about font shape... maybe is the same thing... or something is doing weird things on same pushed pose.
i'll fix it on 1.3.0. or if any other bug with enough justification to need a release appears to put fix there.

**Comment by SrRapero720** [comment]
wtf with tags...

**Comment by SrRapero720** [comment]
## FIXED VERSION
- CurseForge: [1.18.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026253) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026255) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026257)
- Modrinth: [1.18.2](https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.2) | [1.19.2](https://modrinth.com/mod/embeddiumplus/version/1.19.2-v1.2.2) | [1.20.1](https://modrinth.com/mod/embeddiumplus/version/1.20.1-v1.2.2)
