### ISSUE TITLE
Dynamic lighting stopped working when throwing objects in new versions along with RyoamicLights

### ISSUE THREAD

**Issue by Krimatoria** [SrRapero720/chloride#27]
Forge 1.19.2-43.3.7 
Embeddium-0.2.16+mc1.19.2.jar
Rubidium-extra-0.4.19+mc1.19.2-build.105.jar
Textrues_embeddium_options-0.1.1+mc1.19.2.jar

I just installed the mods, dynamic lighting is enabled in the settings of both mods.
Dynamic lighting when dropping a torch and other light sources does not work in Embeddium++ versions higher than 1.1.0 (1,2,2, 1.2.1, 1.2.0) along with RyoamicLights 0.1.5. The latest version 

It works 100% in Embeddium++ version 1.1.0 + RyoamicLights 0.1.5
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/6815e164-a40f-46b0-ab94-821fdbe5e56b)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/07a135e1-45ad-476f-9860-bbc9be21860d)

**Comment by SrRapero720** [comment]
1. RyoamicDynLights ia NOT SUPPORTED (Both derivates from the same code, have to remove it btw)
2. Issue was fixed in 1.2.2

## DOWNLOAD FIXED VERSIONS
- CurseForge: [1.18.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026253) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026255) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026257)
- Modrinth: [1.18.2](https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.2) | [1.19.2](https://modrinth.com/mod/embeddiumplus/version/1.19.2-v1.2.2) | [1.20.1](https://modrinth.com/mod/embeddiumplus/version/1.20.1-v1.2.2)

**Comment by Krimatoria** [comment]
> 1. RyoamicDynLights НЕ ПОДДЕРЖИВАЕТСЯ (оба происходят из одного и того же кода, кстати, его нужно удалить)
> 2. Проблема была исправлена ​​в версии 1.2.2.
> 
> ## СКАЧАТЬ ФИКСИРОВАННЫЕ ВЕРСИИ
> * CurseForge: [1.18.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026253) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026255) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/embeddium-plus/files/5026257)
> * Модринт: [1.18.2](https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.2) | [1.19.2](https://modrinth.com/mod/embeddiumplus/version/1.19.2-v1.2.2) | [1.20.1](https://modrinth.com/mod/embeddiumplus/version/1.20.1-v1.2.2)

Nope)))) It doesn't work)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/024047af-5acc-4845-b5d7-28b785fcaf19)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/e0c4fa68-1881-4dbe-b4bc-ccd249f2bcd2)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/bd5ef691-c019-403e-afa4-ed46feec47d2)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/b663105a-2158-436e-99ac-8131744866cf)

**Comment by SrRapero720** [comment]
works with shaders disabled?

**Comment by Krimatoria** [comment]
> работает с отключенными шейдерами?

No)))) Turned off the shaders.
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/3d77673f-5b40-4b61-ba0b-5a981ef8605c)

**Comment by SrRapero720** [comment]
and turning off-on dynlights again make it work?

**Comment by Krimatoria** [comment]
> и снова выключить и включить динамическое освещение, все заработает?

Oh, I even created a new world on the superplane to test everything from 0. It works in the hand, as always. But it won't work if you throw it away, even though it worked with Ryoamiclights in 1.1.0. Yes, I turned off the shaders and turned on and off dynamic lighting several times. Nothing changes.
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/3409a0bb-723a-439a-9851-058b15e7a191)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/3373e0d5-8236-499d-a34c-c5f8717c8851)

**Comment by SrRapero720** [comment]
may i miss something?

whoever, try to don't use RyoamicDynlights with emb++. basically both mods do the same, and the only you are archieveing is spam chunk updates 2 times, and is not a worth result on client-side TPS/FPS.

i will queue this for 1.3.0, i am working on other things right now.

**Comment by Krimatoria** [comment]
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/3d404447-781d-475c-aba7-2fcfbb4e04b4)
Oh, interesting. First of all, I installed embeddium-0.2.15 instead of embeddium-0.2.16, updated it to a new version, but for some reason it doesn't work there either. But I saw strange stripes near a certain border, I do not even know what it is?

![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/372577e5-4727-435d-aaef-33ce31da05cb)
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/106809386/0da1a3d4-bde1-46d0-a2a8-96de778dfb50)

**Comment by Krimatoria** [comment]
> may i miss something?
> 
> whoever, try to don't use RyoamicDynlights with emb++. basically both mods do the same, and the only you are archieveing is spam chunk updates 2 times, and is not a worth result on client-side TPS/FPS.
> 
> i will queue this for 1.3.0, i am working on other things right now.

Thanks)

**Comment by SrRapero720** [comment]
is some of the consequenses of not know how to make proper customizations (blaming lamb)

> Oh, interesting. First of all, I installed embeddium-0.2.15 instead of embeddium-0.2.16, updated it to a new version, but for some reason it doesn't work there either. But I saw strange stripes near a certain border, I do not even know what it is?

i increase dyn-lights range in 1.2.1 (workarround of SrRapero720/EmbeddiumPlus#44), but it cause some minor visual bugs (fixed only doing something to update chunk, like enter on it again with a light)

again, all DynLight fixes will be focused on 1.3.0
https://github.com/SrRapero720/EmbeddiumPlus/milestone/2

**Comment by Krimatoria** [comment]
> это некоторые последствия незнания того, как правильно выполнить настройку (обвинение ягненка)
> 
> > О, интересно. Первым делом я установил embeddium-0.2.15 вместо embeddium-0.2.16, обновил его до новой версии, но он и там почему-то не работает. Но я увидел странные полосы возле некоей границы, я даже не знаю, что это такое?
> 
> я увеличил дальность динамического освещения в 1.2.1 (обходной путь [№ 8](https://github.com/SrRapero720/EmbeddiumPlus/issues/44) ), но это вызвало некоторые незначительные визуальные ошибки (исправлено только выполнение чего-либо для обновления чанка, например, повторный вход в него со светом)
> 
> опять же, все исправления DynLight будут сосредоточены на версии 1.3.0 https://github.com/SrRapero720/EmbeddiumPlus/milestone/2

Good luck) If I see anything, I'll let you know)
