### ISSUE TITLE
disabling f11 mixin doesn't seem to work

### ISSUE THREAD

**Issue by LeoBeliik** [SrRapero720/chloride#28]
I've disabled the 'enable borderless on f11' in the config and restarted the game but the f11 still goes thru fullscreen -> borderless -> window mode.
f11 is set to false in embeddium++mixin.toml

embeddium-0.2.16+mc1.20.1
embeddiumplus-1.20.1-v1.2.2
textrues_embeddium_options-0.1.3+mc1.20.1
tested with forge 47.1.3 & 47.2.6

**Comment by Exzept1on** [comment]
Can confirm

**Comment by SrRapero720** [comment]
Fixed, pending release

**Comment by SrRapero720** [comment]
## DOWNLOAD FIXED VERSION
- CurseForge: [1.18.2](https://www.curseforge.com/minecraft/mc-mods/embeddiumplus/files/5051375) | [1.19.2](https://www.curseforge.com/minecraft/mc-mods/embeddiumplus/files/5051377) | [1.20.1](https://www.curseforge.com/minecraft/mc-mods/embeddiumplus/files/5051407)
- Modrinth: [1.18.2](https://modrinth.com/mod/embeddiumplus/version/1.18.2-v1.2.3) | [1.19.2](https://modrinth.com/mod/embeddiumplus/version/1.19.2-v1.2.3) | [1.20.1](https://modrinth.com/mod/embeddiumplus/version/1.20.1-v1.2.3)
