### ISSUE TITLE
Highly probable memory leak issue

### ISSUE THREAD

**Issue by QianFuv** [SrRapero720/chloride#3]
debug.log: https://mclo.gs/M93MCBf

hs_err_pid27444.log: https://mclo.gs/gzQJIAs

latest.log: https://mclo.gs/Xs9VGzP

**Comment by SrRapero720** [comment]
issue appears without the mod?
and how much time takes to get out of memory?

**Comment by QianFuv** [comment]
1. No
2. Almost 30 min

It should be noted that I did not experience this problem with [Rubidium Extras](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras).

**Comment by SrRapero720** [comment]
can you try with this version?
https://github.com/SrRapero720/EmbeddiumPlus/releases/tag/1.19.2-1.4.3

**Comment by QianFuv** [comment]
So far, no memory leaks have been found. However, I believe further testing is necessary. Please wait for my report in a few days.

**Comment by QianFuv** [comment]
> English is not my native language; please excuse typing errors.

I have seen your recent submission: https://github.com/SrRapero720/EmbeddiumPlus/commit/a68be6e3034812c634fbfb9ef16e64874429cd06
[Another mod](https://www.curseforge.com/minecraft/mc-mods/debugify-reforged) in my modpack also includes this feature, and I believe that adding this feature to EmbeddiumPlus is unsafe and inappropriate.
This feature introduced by [Debugify-reforged](https://www.curseforge.com/minecraft/mc-mods/debugify-reforged) works well with [fix GPU memory leak](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak) and [MemoryLeakFix](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix), and currently no memory leak issues are encountered with these three, but I don't know why there is a serious memory leak issue in EmbeddiumPlus.
All in all, this should be one of the main causes of memory leaks, the problem should be solved, thank you for your efforts!
I hope you've thought carefully when adding new features, because Embeddium is a premium mod and I want its affiliates to be as good as it is!
If there are any further issues in the future, I will continue to report them.

**Comment by SrRapero720** [comment]
@Qian-F 
That change was reverted on build i send you. I suspect what can be the cause, when you say It no happens on Rubidium extras.

That change is pretty small and safe to implement, because Is only inject and cancel, and if any other mod do the same doesnt affect much, i can keep It without break other mods (unless i confirm my suspects of is leaking)

The major issue was caused by whitelist feature, i still dont understand why causes leak but is great know was fixed :)

Update queue for 1.0.1

**Comment by QianFuv** [comment]
I may have misunderstood the cause of the problem, but all in all the problem has been solved. Thank you for your efforts!

**Comment by QianFuv** [comment]
Unfortunately, the problem still exists, as soon as I add this mod to my modpack, I experience a memory leak

**Comment by SrRapero720** [comment]
then i have a big problem, if issue never occurs with Magnesium/Rubidium Extras but occurs with Emb++ then that means i mess up something on porting to 1.19.2

i need do more research, at the moment. i need help

**Comment by QianFuv** [comment]
The most recent crash error report can be found [here](https://legacy.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak/issues/3). I have provided feedback to the author of `fix GPU memory leak` because his mod did not address the issue of `GL_OUT_OF_MEMORY` memory leak, which is also the problem I encountered after installing `Emb++`.
I will test it again after waking up to make sure that this issue won't occur in `Rubidium Extras`.

**Comment by QianFuv** [comment]
In my tests, the previous feedback needs to be modified. In my tests, both `Emb++` and `Rubidium Extras` cause GPU memory leaks. This may be because they make the function of `fix GPU memory leak mod` ineffective.
I am deeply sorry for the wrong conclusion I reached earlier!

**Comment by SrRapero720** [comment]
try installing farsight. problem persists?

**Comment by QianFuv** [comment]
I will try it later.
Please wait my feedback.

**Comment by QianFuv** [comment]
One small problem is that I'm not playing on the server, just in single player, and I'm not sure that farsight will work in single player.

**Comment by QianFuv** [comment]
![Screenshot_2023-12-21-14-31-45-13_4d38fce200f96aeac5e860e739312e76.png](https://github.com/SrRapero720/EmbeddiumPlus/assets/111696321/70c84f82-701a-453a-85c3-c1354d1cb4d7)

someaddon replied to me saying "does work, but it only prevents a couple bugs can't prevent all issues^^", possibly because emb++ is causing a new GPU memory leak problem? So far I am not experiencing crashes with emb++ disabled(I am playing my modpack intensively to prevent the possibility of misreporting.).

**Comment by QianFuv** [comment]
I will test it today. Sorry for these two days I don't check it...

**Comment by QianFuv** [comment]
I did a simple 30-minute test and everything seems normal. I'll do another hour-long test after waking up.

**Comment by QianFuv** [comment]
> try installing farsight. problem persists?

Crash also: https://mclo.gs/IJumAKr

**Comment by QianFuv** [comment]
https://github.com/embeddedt/embeddium/issues/85 ← this issue may help
https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility ← sodium wiki
