### ISSUE TITLE
Crash trying to enter the world (v1.2.1)

### ISSUE THREAD

**Issue by notnotype** [SrRapero720/chloride#30]
```
java.lang.AbstractMethodError: Receiver class net.minecraft.client.player.LocalPlayer does not define or inherit an implementation of the resolved method 'boolean tdv$isDynamicLightEnabled()' of interface me.srrapero720.embeddiumplus.foundation.dynlights.accessors.DynamicLightSource.
```

[crash-2024-01-15_12.16.49-client.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/13934773/crash-2024-01-15_12.16.49-client.txt)

Works well in 1.0.1
embeddium version: 0.2.16

**Comment by SrRapero720** [comment]
send me your logs, your crash report say nothing and looks like emb++ mixins aren't applied

**Comment by notnotype** [comment]
[2024-01-15-2.log](https://github.com/SrRapero720/EmbeddiumPlus/files/13935498/2024-01-15-2.log)

**Comment by notnotype** [comment]
[minecraft-exported-crash-info-2024-01-15T14-21-10.zip](https://github.com/SrRapero720/EmbeddiumPlus/files/13935532/minecraft-exported-crash-info-2024-01-15T14-21-10.zip)

**Comment by SrRapero720** [comment]
You have another mod of Dynamic lights installed
You had to remove Dynamic lights Reforged
Emb++ already includes it.
