### ISSUE TITLE
Pitch_black not affected by moon phase

### ISSUE THREAD

**Issue by Aceplante** [SrRapero720/chloride#31]
Title. When choosing the Pitch_black darkness option, it does not seem to be effected by the moon phase

forge 1.20.1

**Comment by Aceplante** [comment]
Edit, now it is, but pitch black is not pitch black

**Comment by SrRapero720** [comment]
leveling of darkness is
really dark -> pitch black -> dark -> dim

**Comment by Aceplante** [comment]
> leveling of darkness is really dark -> pitch black -> dark -> dim

ah, You'd think pitch black would be the darkest

**Comment by SrRapero720** [comment]
In code and config file is specified the dark ordering. Not sure if i should use pitch black for the darkest one, but is fine for me.
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/29090346/bb2d2239-10d4-438e-9e89-79117d128314)
