### ISSUE TITLE
Modrinth page for Embeddium++ is missing?

### ISSUE THREAD

**Issue by TrueVoidwalkerx** [SrRapero720/chloride#37]
I was checking my mods for updates, and it said that Embeddium++ isn't available on Modrinth, which is where I downloaded it from. I checked the main website, and sure enough it's no longer there. The CurseForge page is still there.

Is there a reason this is the case or is it a mistake?

**Comment by SrRapero720** [comment]
licenses, drama, modrinth and loans... is the most short version of it.
modrinth take it down, will be back... eventually. no ETAs.

**Comment by SrRapero720** [comment]
Emb++ will stop begin updated on modrinth after release 1.3.0
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/29090346/85e0d703-1119-44bf-b589-ed0db03a468d)
