### ISSUE TITLE
Invisible chests when Fast Chests is enabled

### ISSUE THREAD

**Issue by DTech10** [SrRapero720/chloride#38]
only visible if its a double chest
[Latest Logs](https://mclo.gs/bs8hJxH)

![2024-02-06_15 52 09](https://github.com/SrRapero720/EmbeddiumPlus/assets/136813833/1933b858-2925-4233-8a62-1b1641c569d0)

![2024-02-06_15 02 26](https://github.com/SrRapero720/EmbeddiumPlus/assets/136813833/9e0b2244-e313-485c-a418-b44b09f2e612)

**Comment by SrRapero720** [comment]
duplicate of SrRapero720/EmbeddiumPlus#100
