### ISSUE TITLE
Video Settings Crash on click

### ISSUE THREAD

**Issue by spacingfox11** [SrRapero720/chloride#43]
Every time I click on video settings it automatically crashes, no buts or why s.
[crash.txt](https://github.com/SrRapero720/EmbeddiumPlus/files/14365734/crash.txt)

**Comment by SrRapero720** [comment]
[23:51:37] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'embeddium', Requested by: 'embeddiumplus', Expected range: '[0.2.5,)', Actual version: '[MISSING]'
	Mod ID: 'embeddium', Requested by: 'textrues_embeddium_options', Expected range: '[0.1,)', Actual version: '[MISSING]'

**Comment by spacingfox11** [comment]
I have both of them. It just wouldn't load and I already tried reinstalling completely minecraft.

**Comment by SrRapero720** [comment]
update textrues_embeddium_options to LATEST (0.1.5) you're using 0.1.3
your logs are bastardized with other logs session and really make me miss things

WHOEVER. My suggestion is DON'T USE TLAUNCHER, is a malware/spyware. Please reinstall your OS and use safe alternatives like SKLauncher or consider buy the game to use the official launcher or the CurseForge one

**Comment by spacingfox11** [comment]
Sorry for the messy logs. The update worked but not entirely, I also had to update embeddium to 0.2.5 as the lastest wtv version it had did not work.
Will take the advice with the launcher, currently still looking for a better launcher.
