### ISSUE TITLE
Embeddium++ latest update breaks REI

### ISSUE THREAD

**Issue by Desoroxxx** [SrRapero720/chloride#46]
With Embeddium++ I cannot look any recipes or uses of any entries in REI, **this only happens since the latest update**.

**Comment by SrRapero720** [comment]
That's a feature, disable "Hide JEI/REI/EMI until searching" on config, is disabled by default

**Comment by Desoroxxx** [comment]
No, I can see the items, blocks, etc.. but clicking on them or pressing r or u does nothing

**Comment by SrRapero720** [comment]
moved to #47
