### ISSUE TITLE
Newest update (1.2.6) breaks Roughly Enough Items

### ISSUE THREAD

**Issue by MCCrafter247** [SrRapero720/chloride#47]
Minecraft 1.20.1
Forge 47.2.20
Latest versions of Roughly Enough Items, Embeddium++. and all dependencies, as shown in the image

![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/108512960/4f290bfa-a5cf-4899-937f-f68de6e62d9f)

Error description: In any GUI, you cannot click on the REI menu, be it the buttons to change page, the items themselves, etc. For some reason I can click the config button, but that's it. Interacting with any of the following parts does nothing via mouse click. The same goes for any keyboard interactions with it. Oddly enough, using the scroll wheel changes page, but using any other button (such as R and U to view recipes, mouse click, etc.) does not work.

![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/108512960/d0327f61-c229-444b-a97a-22268356fbe2)

Here are the latest logs for my game as well. I deleted the old one, then just launched the game, opened a world, and attempted to interact with REI's menu in all the ways I normally would. That should minimize any clutter from past loads and make it easier. I hope this provides some useful info. https://pastebin.com/chaQLxiu

If you need any more info, let me know. The game is basically unplayable in a large modpack. I would just switch to JEI, but JEI does not work with Fabric mods loaded through Sinytra Connector. Only REI allows me to view the recipes and items of both loaders at once, as long as I have ConnectorExtras installed. 

After some additional testing, it seems both JEI and EMI work as intended, meaning this is exclusive to REI. Until this is fixed, I'll have to settle for using Embeddium++ version 1.2.5, and Zume version 0.17.0 in my bigger modpack.

**Comment by SrRapero720** [comment]
the day i made the mixin i was just brainless.
i fixed the bug, thanks for the reports
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/29090346/94bd69c1-a27f-4e81-8884-5ef37e440ca6)

**Comment by Desoroxxx** [comment]
> i fixed the bug, thanks for the reports

Did you forget to publish an update or will it come out later?
