### ISSUE TITLE
New Embeddium update marked textrue embeddium options incompatible

### ISSUE THREAD

**Issue by DeshiDesu** [SrRapero720/chloride#55]
https://github.com/embeddedt/embeddium/issues/276

**Comment by SrRapero720** [comment]
Embeddium++ doesn't longer mark embeddium options as a required dependency, you can remove it and mod will start

**Comment by DeshiDesu** [comment]
Sorry, my launcher said it needed textrue I thought it was a hard dependency

**Comment by mpustovoi** [comment]
Please push new 1.2.8 version to Modrinth
