### ISSUE TITLE
Textrue’s Embeddium Options was discontinued.

### ISSUE THREAD

**Issue by PeglinX** [SrRapero720/chloride#57]
As the title says Embeddium Options was discontinued because It was merged unto embeddium yet this mod still asks for it to work

**Comment by DeshiDesu** [comment]
> As the title says Embeddium Options was discontinued because It was merged unto embeddium yet this mod still asks for it to work

It asks for it but you can just ignore that message. Completely works fine without textrue. I do agree it's a bit annoying though

**Comment by Magi1053** [comment]
My game crashes on launch because TEO is missing

**Comment by SrRapero720** [comment]
UPDATE
THE
MOD
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/29090346/f9b8b8ab-f00f-495f-b1c4-60265ef3b9dc)

**Comment by PeglinX** [comment]
The report was made 1 day before the patch

**Comment by EnderFS** [comment]
Update mod for 1.20.4 version please
