### ISSUE TITLE
Add entity block culling (Create mod)

### ISSUE THREAD

**Issue by NeoFolia** [SrRapero720/chloride#63]
FPS lags very much due to mechanisms from the Create mod, it would be cool if they could make a rejection distance for mechanisms and blocks from the Create mod.

**Comment by SrRapero720** [comment]
you can add by youself in the mod config
open the config
and add where says "culling whitelist" (or similar) the Create resource location

if you want to EMB++ ignore all create stuff just put `create:*` and everything (of create) will be ignored

**Comment by NeoFolia** [comment]
No working your function. Create blocks/EntityTileBlock activate mechanism visible.

**Comment by NeoFolia** [comment]
I specified culling - 16 blocks, but I see mechanisms for 64+ blocks.

**Comment by NeoFolia** [comment]
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/147491823/67eeaf6d-07ea-4882-a247-b86bb32cade3)

**Comment by NeoFolia** [comment]
all mechanism visible.
![image](https://github.com/SrRapero720/EmbeddiumPlus/assets/147491823/76279445-5dff-4bfe-a0c3-aa4596f66e77)

**Comment by NeoFolia** [comment]
config 
[embeddium++.txt](https://github.com/user-attachments/files/15594277/embeddium%2B%2B.txt)

**Comment by NeoFolia** [comment]
Your setup does not work with any block/entity/mechanism from Create. Checked and confirmed.

**Comment by SrRapero720** [comment]
can you send me your logs?

**Comment by NeoFolia** [comment]
[latest.log](https://github.com/user-attachments/files/15594493/latest.log)
[debug.log](https://github.com/user-attachments/files/15594494/debug.log)

**Comment by SrRapero720** [comment]
GIST https://gist.github.com/SrRapero720/c87c0e5115da9e1e0fb3231d21888b61

**Comment by NeoFolia** [comment]
???

**Comment by NeoFolia** [comment]
What does it mean?

**Comment by SrRapero720** [comment]
i checked many times and it seems like everything is working... so is odd... create contraptions should be culled

**Comment by SrRapero720** [comment]
OK i see what is happening
Create uses their own rendering API (flywheel) which do rendering outside Minecraft rendering
but _that means all "should cull"_ code is ignored.

You can fix it using `/flywheel backend off`. so EMB++ can cull it.
otherwise it will still use Flywheel backed (and by extension... ignore all "should cull" conditions)
