### ISSUE TITLE
`1.20.1` Crash when joining the world

### ISSUE THREAD

**Issue by mpustovoi** [SrRapero720/chloride#65]
The game crashes after `Joining the world...` screen on `Forge 1.20.1`
There may be a compatibility problem with another mod, since, for example, after updating `Embeddium` to `0.3.20` everything was working fine.
[Crash-report and latest.log](https://gist.github.com/mpustovoi/92eec4a4bf0de4673a06befb58262a9e)

Here is a list of all the mods of my custom modpack that have been updated, and after what the problem appeared, if it helps narrow down the suspects:
- [`Alex's Mobs Interaction`](https://modrinth.com/mod/alexs-mobs-interaction)
- [`AzureLib`](https://modrinth.com/mod/azurelib)
- [`BadOptimizations`](https://modrinth.com/mod/badoptimizations)
- [`Bookshelf`](https://modrinth.com/mod/bookshelf-lib)
- [`Elytra Slot`](https://modrinth.com/mod/elytra-slot)
- [`[ETF] Entity Texture Features`](https://modrinth.com/mod/entitytexturefeatures)
- [`Forgotten Graves`](https://modrinth.com/mod/forgotten-graves) (via `Sinytra Connector`)
- [`Geckolib`](https://modrinth.com/mod/geckolib)
- [`Just Enough Items`](https://modrinth.com/mod/jei)
- [`My Nether's Delight`](https://modrinth.com/mod/my-nethers-delight)
- [`Packet Fixer`](https://modrinth.com/mod/packet-fixer)
- [`Polytone`](https://modrinth.com/mod/polytone)
- [`SeasonHUD`](https://modrinth.com/mod/seasonhud)
- [`Shoulder Surfing Reloaded`](https://modrinth.com/mod/shoulder-surfing-reloaded)

**Comment by mpustovoi** [comment]
Nvm, the problem disappeared the next joining the world. Perhaps something failed to initialize correctly after the updates.

**Comment by mpustovoi** [comment]
Nope, it's still here.

**Comment by soup587** [comment]
i think it may be entity texture features, i recently updated my mods and the only one we have in common is etf

**Comment by VoidLeech** [comment]
This seems to be the same issue as https://github.com/ItsThosea/BadOptimizations/issues/59

**Comment by LordKhaoss** [comment]
Hello,
It seems that the error was solved with update 2.1.3 of the BadOptimizations mod

**Comment by SrRapero720** [comment]
i have to fix this too on my side

**Comment by mpustovoi** [comment]
Yes, the BadOptimizations update did fix this.

**Comment by SrRapero720** [comment]
fixed, thanks for the report
