### ISSUE TITLE
wierd shader crash with light texture and boolean is dirty on generating world

### ISSUE THREAD

**Issue by loti1234** [SrRapero720/chloride#66]
[crash-2024-06-13_15.52.09-client.txt](https://github.com/user-attachments/files/15821601/crash-2024-06-13_15.52.09-client.txt)

[latest.log](https://github.com/user-attachments/files/15821614/latest.log)

**Comment by loti1234** [comment]
1.19.2 ver btw
i used opal shaders

**Comment by loti1234** [comment]
nvm it does that even without shaders

**Comment by LordKhaoss** [comment]
Hello,
It seems that the error was solved with update 2.1.3 of the BadOptimizations mod

**Comment by loti1234** [comment]
yay

**Comment by SrRapero720** [comment]
duplicated of #65
