### ISSUE TITLE
[Suggestion] When config option "Hide JREI" is enabled, add a note somewhere indicating this config is enabled.

### ISSUE THREAD

**Issue by Gbergz** [SrRapero720/chloride#70]
When config option "Hide JREI" is enabled, add a note somewhere indicating this option is enabled.
Maybe when hovering over the search bar or similar.

Would prevent some cases where people report JEI is malfunctioning while it technically isn't.

Thanks.

**Comment by SrRapero720** [comment]
Duplicate of #69
